CREATE TABLE IF NOT EXISTS UserCredentials(
	user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	FOREIGN KEY(user_id) REFERENCES Users(id),
	when_registered DATETIME NOT NULL DEFAULT NOW(),
	email VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL
)