CREATE TABLE IF NOT EXISTS UserCredentials(
	user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	FOREIGN KEY(user_id) REFERENCES Users(id),
	login VARCHAR(100) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	when_registered DATETIME NOT NULL DEFAULT NOW(),
	password VARCHAR(100) NOT NULL
)